### ISSUE TITLE
Create a binding control loop

### ISSUE THREAD

**Issue by krancour** [deis/steward-framework#17]

**Comment by arschles** [comment]
Since `Binding`s are namespace-specific (not cluster-global), this loop will eventually need to:
- Listen on all namespaces
- Start and stop control loops for namespaces that are added and removed, respectively

For this issue to be complete, the loop should just listen on a hard-coded set of namespaces and not dynamically start/stop loops even if those namespaces are removed.

#30 has been created to capture the new work
